services:
  wallettuner-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - wallettuner-server

  wallettuner-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
